Repository wecode-bootcamp-korea/10-Likey-frontend, pull requests merged in 2020-08, with the labels that each got.

#2 [Likey: 최태희] Add: 제품상세페이지 레이아웃 및 사이즈,수량버튼 기능구현
  package-lock.json
  package.json
  public/Data/Data.json
  public/Images/Detail/otherInfo.png
  src/App.css
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/DetailLeft.js
  src/Pages/Detail/DetailLeft.scss
  src/Pages/Detail/DetailRight.js
  src/Pages/Detail/DetailRight.scss
  src/Pages/Detail/Options.js
  src/Pages/Detail/Options.scss
  src/Routes.js
  src/config.js
  src/index.css
Labels: Status: 수정 요청

#6 Modify: 리뷰반영 수정 (API 주소 template literals적용, 불필요한 코드 삭제
  src/Pages/Detail/Detail.js
  src/Pages/Detail/DetailLeft.scss
  src/Pages/Detail/DetailRight.js
  src/config.js
Labels: Status: Accepted

#1 [Likey:이병훈] Refactor : 멘토님 피드백 반영
  public/Images/Main/cart.png
  public/Images/Main/converse.png
  public/Images/Main/filter.png
  public/Images/Main/jordan.png
  public/Images/Main/logo.png
  public/Images/Main/search.png
  public/Images/Main/나이키.png
  public/Images/Main/대한민국.png
  public/Images/Main/화살표내림.png
  public/Images/Main/화살표올림.png
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavData.js
  src/Components/Nav/Secondlist.js
  src/Components/Nav/SubMenu/SubCategories.js
  src/Components/Nav/SubMenu/SubKids.js
  src/Components/Nav/SubMenu/SubKids.scss
  src/Components/Nav/SubMenu/SubMenu.js
  src/Components/Nav/SubMenu/SubMenu.scss
  src/Components/Nav/response.json
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/MainProduct/MainProduct.js
  src/Pages/Main/MainProduct/MainProduct.scss
  src/Pages/Main/mainData.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#4 [Likey : 박민규] Add : 로그인 레이아웃 완성 , 모달 기능 추가
  public/Images/SignIn/facebook.png
  public/Images/SignIn/kakao.png
  public/Images/SignIn/signInIcon.png
  src/Components/SignIn/SignIn.js
  src/Components/SignIn/SignIn.scss
  src/Components/SignIn/button.js
  src/Routes.js
Labels: Status: Accepted

#5 [Likey : 박민규] Add : 회원 가입 레이아웃 완성
  public/Images/Signup/facebook.png
  public/Images/Signup/kakao.png
  public/Images/Signup/twodragon.png
  public/Images/Signup/twodragon2.png
  public/Images/Signup/twodragon3.png
  public/index.html
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
Labels: Status: Accepted

#9 Refactor: 중간발표 후 수정
  public/Images/Cart/cart.png
  src/Components/CartList/CartList.js
  src/Components/CartList/CartList.scss
  src/Components/CartModal/CartModal.js
  src/Components/CartModal/CartModal.scss
  src/Components/CartModal/Dimmer.js
  src/Components/CartModal/Dimmer.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/PageTop/PageTop.js
  src/Components/SignIn/SignIn.js
  src/Components/SignIn/SignIn.scss
  src/Components/SignIn/button.js
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/DetailRight.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Routes.js
  src/Styles/Common.scss
  src/config.js
Labels: Status: Accepted

#8 [Likey : 박민규] Modify : 불필요한 코드 정리 & 리뷰 반영
  public/Images/Loading/ajax-loader.gif
  src/Components/CartList/CartList.js
  src/Components/CartList/CartList.scss
  src/Components/LoadingModal/LoadingModal.js
  src/Components/LoadingModal/LoadingModal.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/SubMenu/SubKids.js
  src/Components/Nav/SubMenu/SubMenu.js
  src/Components/SignIn/SignIn.js
  src/Components/SignIn/SignIn.scss
  src/Components/SignIn/button.js
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Detail/Detail.js
  src/Pages/SignUp/SignUp.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#7 [Likey : 최태희] Add: 장바구니 미니모달창 레이아웃
  package.json
  src/Components/CartModal/CartModal.js
  src/Components/CartModal/CartModal.scss
  src/Components/CartModal/Dimmer.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/DetailLeft.scss
  src/Pages/Detail/DetailRight.js
  src/Pages/Detail/DetailRight.scss
  src/config.js
  yarn.lock
Labels: Status: 수정 요청

#10 [Likey:이병훈]Fix : Conflict 해결 및 기능구현 test 완료
  package-lock.json
  src/Components/CartModal/CartModal.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/SubMenu/SubKids.js
  src/Components/Nav/SubMenu/SubKids.scss
  src/Components/Nav/SubMenu/SubMenu.js
  src/Components/Nav/SubMenu/SubMenu.scss
  src/Components/SignIn/SignIn.scss
  src/Pages/Cart/Cart.js
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/Options.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/MainProduct/MainProduct.js
  src/Pages/Main/MainProduct/MainProduct.scss
  src/Pages/Main/Products/Products.js
  src/Pages/Main/Products/Products.scss
  src/Pages/Main/mainData.js
  src/Pages/SignUp/SignUp.js
  src/Routes.js
  src/config.js
Labels: Status: 도움 요청, Status: 리뷰 요청
